// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGMy8oBBJvdFTxfwdKAjQEPjeoMyrr5dw',
    appId: '1:720843739369:web:230b159cecf77f1a8ca078',
    messagingSenderId: '720843739369',
    projectId: 'flutter-app-b8aed',
    authDomain: 'flutter-app-b8aed.firebaseapp.com',
    storageBucket: 'flutter-app-b8aed.appspot.com',
    measurementId: 'G-C2Z6K47L52',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmVa_w9t5RSWBtohWpbnPtnJmxA18D4Yg',
    appId: '1:720843739369:android:55e0fb069f620feb8ca078',
    messagingSenderId: '720843739369',
    projectId: 'flutter-app-b8aed',
    storageBucket: 'flutter-app-b8aed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4rZZUQJDynbmeQ2sR70tZSweHt7MJtu0',
    appId: '1:720843739369:ios:a071af020b669ada8ca078',
    messagingSenderId: '720843739369',
    projectId: 'flutter-app-b8aed',
    storageBucket: 'flutter-app-b8aed.appspot.com',
    iosBundleId: 'com.example.firebaseLab1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4rZZUQJDynbmeQ2sR70tZSweHt7MJtu0',
    appId: '1:720843739369:ios:7a988c24581ec2a28ca078',
    messagingSenderId: '720843739369',
    projectId: 'flutter-app-b8aed',
    storageBucket: 'flutter-app-b8aed.appspot.com',
    iosBundleId: 'com.example.firebaseLab1.RunnerTests',
  );
}
